# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            # entity: { class: AppBundle:User, property: email }
            chain:
              providers: ['db_email', 'db_username']
        db_email:
            entity: { class: AppBundle:User, property: email }
        db_username:
            entity: { class: AppBundle:User, property: username }

    firewalls:
    # when symfony boots it only uses one firewall. if you are on /api/something then the api-firewall will be used else the main
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            anonymous: true

        doc:
            pattern: ^/api/doc
            anonymous: true

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # allow anonymous API - if auth is needed, it's handled in the controller
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: IS_AUTHENTICATED_FULLY }