# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    api_problem_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ['@api.response_factory', %kernel.debug%]
        tags:
            - { name: kernel.event_subscriber }

    pagination_factory:
        class: AppBundle\Pagination\PaginationFactory
        arguments: ['@router']

    link_serialization_subscriber:
        class: AppBundle\Serializer\LinkSerializationSubscriber
        arguments: ['@router', '@annotation_reader']
        tags:
            - { name: jms_serializer.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    api.response_factory:
        class: AppBundle\Api\ResponseFactory

    app.doctrine.hash_password_listener:
        class: AppBundle\EventListener\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }