# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path: /logout

            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER: []
        ROLE_ADMIN: ['ROLE_ALLOWED_TO_SWITCH', 'ROLE_BACKEND_ACCESS']
        ROLE_USER_MANGE: ['ROLE_BACKEND_ACCESS', 'ROLE_USER_EDIT', 'ROLE_USER_CREATE']